FROM lakoo/android-ndk

RUN sed -i 's#deb.debian.org#mirrors.ustc.edu.cn#g' /etc/apt/sources.list && sed -i 's/sid/bullseye/g' /etc/apt/sources.list

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0E98404D386FA1D9 6ED0E7B82643E131

RUN apt -y update

RUN apt -y install lsb-release

RUN lsb_release -a

RUN apt update && apt -y full-upgrade

RUN apt -y autoclean

RUN lsb_release -a

RUN apt update && apt install -y automake libtool make cmake flex bison

